-- Simple Secrets: Lean 4 Security Properties Modeling
-- High-level model of k-in-n threshold secret sharing & ML-KEM Correctness

def Share := Nat
def Secret := Nat

-- ---------------------------------------------------------
-- 1. Secret Sharing Scheme Modeling
-- ---------------------------------------------------------

structure SecretSharingScheme where
  n : Nat
  k : Nat
  generate : Secret → List Share
  reconstruct : List Share → Option Secret

-- Property 1: Correctness
-- Any subset of at least `k` of the generated shares reconstructs the secret.
def Correctness (s : SecretSharingScheme) : Prop :=
  ∀ (sec : Secret) (shares : List Share),
    shares = s.generate sec →
    ∀ (subset : List Share),
      subset.Sublist shares →
      subset.length ≥ s.k →
      s.reconstruct subset = some sec

-- Property 2: Authenticated reconstruction (matches the implementation).
-- The Rust `multisig::reconstruct_secret` appends an integrity tag *inside* the
-- shared payload, so a reconstruction attempt from fewer than `k` shares is
-- *rejected* (returns `none`) rather than silently yielding a wrong secret.
-- (The bare `shamir::reconstruct` interpolation has no such guard; this models
-- the multisig API the application actually uses.)
def SubThresholdRejected (s : SecretSharingScheme) : Prop :=
  ∀ (sec : Secret) (shares : List Share),
    shares = s.generate sec →
    ∀ (subset : List Share),
      subset.Sublist shares →
      subset.length < s.k →
      s.reconstruct subset = none

-- Property 3: Perfect secrecy is an *information-theoretic* statement, not a
-- claim about reconstruct's return value: the view of any fewer-than-k shares is
-- independent of the secret. We state it abstractly over a `view` of a subset; a
-- full proof would instantiate `view` with the share bytes and show that two
-- equal-size sub-threshold views are indistinguishable across any two secrets.
def PerfectSecrecy (s : SecretSharingScheme) (view : List Share → Nat) : Prop :=
  ∀ (sec₁ sec₂ : Secret) (sub₁ sub₂ : List Share),
    sub₁.Sublist (s.generate sec₁) →
    sub₂.Sublist (s.generate sec₂) →
    sub₁.length < s.k →
    sub₂.length = sub₁.length →
    view sub₁ = view sub₂

-- ---------------------------------------------------------
-- 2. ML-KEM Protocol Modeling
-- ---------------------------------------------------------

def PublicKey := Nat
def SecretKey := Nat
def SharedSecret := Nat
def Ciphertext := Nat

-- A Key Encapsulation Mechanism (KEM) is defined by three algorithms
structure KEMScheme where
  keygen : Unit → (PublicKey × SecretKey)
  encaps : PublicKey → (Ciphertext × SharedSecret)
  decaps : SecretKey → Ciphertext → Option SharedSecret

-- Property 3: ML-KEM Correctness
-- For any keypair generated by keygen, if we encapsulate a shared secret 
-- against the public key, decapsulating the resulting ciphertext with the 
-- secret key MUST yield the exact same shared secret.
def KEMCorrectness (kem : KEMScheme) : Prop :=
  ∀ (pk : PublicKey) (sk : SecretKey) (ct : Ciphertext) (ss : SharedSecret),
    (pk, sk) = kem.keygen () →
    (ct, ss) = kem.encaps pk →
    kem.decaps sk ct = some ss

-- ---------------------------------------------------------
-- 3. Worked example: a discharged (non-`sorry`) theorem
-- ---------------------------------------------------------
-- This proves the model is not vacuous — `SubThresholdRejected` is satisfiable
-- with an actual proof. A scheme whose `reconstruct` never succeeds trivially
-- rejects every sub-threshold subset. (The real GF(2^8) Shamir+tag scheme is the
-- substantive instantiation to prove next; see PLAN.md Phase F.)

def neverScheme (n k : Nat) : SecretSharingScheme where
  n := n
  k := k
  generate := fun _ => []
  reconstruct := fun _ => none

theorem neverScheme_subThresholdRejected (n k : Nat) :
    SubThresholdRejected (neverScheme n k) := by
  intro _sec _shares _hgen subset _hsub _hlt
  rfl

-- Future work (require concrete scheme instantiations):
-- theorem shamir_correctness : Correctness shamir_scheme := sorry
-- theorem ml_kem_correctness : KEMCorrectness ml_kem_scheme := sorry
